dist: jammy

language: node_js

node_js:
- 18
- 20

cache:
  npm: false

before_install:
  - npm --version

script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run lint
- npm run check-packages

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 18
    branch: main