name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-and-test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm --version
          npm ci

      - name: Run Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test-unit-travis

      - name: Run Lint
        run: npm run lint

      - name: Check Packages
        run: npm run check-packages

  release:
    if: "github.ref_name == 'main' && github.event_name != 'pull_request'"
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build dist folder for release
        run: npm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release